name: Build Gradle project
on:
  pull_request:
    types:
      ready_for_review
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Gradle Cache
        uses: burrunan/gradle-cache-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: sample/gradlew build

      - name: Run Test
        run: sample/gradlew test